# Generated by Django 5.0.4 on 2026-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('JA', 'Java'), ('CS', 'C#')], default='PY', max_length=20),
        ),
    ]
