# Generated by Django 6.0.3 on 2026-03-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_post', 'Can approve post')]},
        ),
    ]
